### ISSUE TITLE
Update SG queries on Cron job to use pagination

### ISSUE THREAD

**Issue by NanezX** [rainprotocol/rain-studio#120]
There is a relevant issue on the cron job, because the queries are not returning all the entities that are stored. This is due the limitation of the response up to aprox 100 entities. Some possibles solutions are:

 - Using pagination. See on thegraph [docs](https://thegraph.com/docs/en/querying/graphql-api/#pagination). But maybe in future we need to use other approach when the data is too big (?) and slow to iterate.
 - Another possible way is save the latest timestamp checked by the cron job on supabase

**Comment by hardyjosh** [comment]
@NanezX I think it makes sense to check the most recent block/timestamp for any fetched data and start from there.

**Comment by NanezX** [comment]
Okay, the cron job has been running since yesterday and the average execution time is not to my liking.

Although the code is functional, it needs optimization as naturally the subgraph data will increase (and we will add more subgraphs in the future).

So the best and logical solution is created a new table on the supabase database, maybe called `networks` or other name. Here we can store relevant information related for each network that we can use on studio. My first thought of this is the following table:

| ID (uuid)* | created_at (timestamp)* | chainId | interpreterUrlSG | 
| ---------- | ------------------------ | ------- | ----------------- | 
| UUID generated | Time when the row was added | chain Id for the network | URL endpoint for interprerter subgraph |


It is very basic and only intended to meet the cronjob requirements, but of course this allow us to add more columns if we need. @hardyjosh

**Comment by NanezX** [comment]
> @NanezX I think it makes sense to check the most recent block/timestamp for any fetched data and start from there.

Ok cool, then I'll leave the PR and ticket open to change the code after closing the selection for contracts
